use_frameworks!

source 'git@bitbucket.org:juwencheng/privatespecrepo.git'
source 'https://github.com/cocoapods/specs.git'
target 'JWCRangeView_Example' do
  pod 'JWCRangeView', :path => '../'

  target 'JWCRangeView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
